---
# tasks file for ./roles/clinic

  - name: Start SonarQube service
    shell: sudo sonarstart restart

  - name: Start Nexus service
    shell: sudo service nexus restart

  - name: Start Tomcat Service
    shell: sudo tomcatup

#  - name: Start Docker service
#shell: sudo service docker restart
